name: torch-nightly
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - fastapi
      - transformers
      - uvicorn
